version: '2.2'
services: 
  elk01:
    image: yongxinl/elkstack-alpine:6.8 
    container_name: elk01
    restart: always
    environment: 
      - node.name=elk01
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits: 
      memlock:
        soft: -1
        hard: -1
    volumes: 
      - /opt/containerd/elasticsearch/data:/usr/share/elasticsearch/data
    ports: 
      - 5601:5601
      - 9200:9200