# ======================== Elasticsearch Configuration =========================
#
# NOTE: Elasticsearch comes with reasonable defaults for most settings.
#       Before you set out to tweak and tune the configuration, make sure you
#       understand what are you trying to accomplish and the consequences.
#
# The primary way of configuring a node is via this file. This template lists
# the most important settings you may want to configure for a production cluster.
#
# Please consult the documentation for further information on configuration options:
# https://www.elastic.co/guide/en/elasticsearch/reference/index.html
#
# ---------------------------------- Cluster -----------------------------------
#
# Use a descriptive name for your cluster:
#
#cluster.name: my-application
#
cluster.name: "elk"
# ------------------------------------ Node ------------------------------------
#
# Use a descriptive name for the node:
#
#node.name: node-1
#
# Add custom attributes to the node:
#
#node.attr.rack: r1
#
# ----------------------------------- Paths ------------------------------------
#
# Path to directory where to store the data (separate multiple locations by comma):
#
# path.data: /path/to/data
#
# path.data: /data/elasticsearch/data
# Path to log files:
#
# path.logs: /path/to/logs
#
# path.logs: /data/elasticsearch/logs
# ----------------------------------- Memory -----------------------------------
#
# Lock the memory on startup:
#
#bootstrap.memory_lock: true
#
# Make sure that the heap size is set to about half the memory available
# on the system and that the owner of the process is allowed to use this
# limit.
#
# Elasticsearch performs poorly when the system is swapping the memory.
#
# ---------------------------------- Network -----------------------------------
#
# Set the bind address to a specific IP (IPv4 or IPv6):
#
#network.host: 192.168.0.1
#
# Set a custom port for HTTP:
#
http.port: 9200
#
# For more information, consult the network module documentation.
# <http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html>
#
network.host: 0.0.0.0
# --------------------------------- Discovery ----------------------------------
#
# Pass an initial list of hosts to perform discovery when new node is started:
# The default list of hosts is ["127.0.0.1", "[::1]"]
#
#discovery.zen.ping.unicast.hosts: ["host1", "host2"]
#
# Prevent the "split brain" by configuring the majority of nodes (total number of master-eligible nodes / 2 + 1):
#
#discovery.zen.minimum_master_nodes: 3
#
# For more information, consult the zen discovery module documentation.
#
# <http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-discovery.html>
#
# minimum_master_nodes need to be explicitly set when bound on a public IP
# set to 1 to allow single node clusters
# Details: https://github.com/elastic/elasticsearch/pull/17288
#
discovery.zen.minimum_master_nodes: 1
# ---------------------------------- Gateway -----------------------------------
#
# Block initial recovery after a full cluster restart until N nodes are started:
#
#gateway.recover_after_nodes: 3
#
# For more information, consult the gateway module documentation.
# <http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-gateway.html>
#
# ---------------------------------- Index -----------------------------------
# You can set a number of options (such as shard/replica options, mapping
# or analyzer definitions, translog settings, ...) for indices globally,
# in this file.
#
# Since elasticsearch 5.x index level settings can NOT be set on the nodes 
# configuration like the elasticsearch.yaml, in system properties or command line 
# arguments.In order to upgrade all indices the settings must be updated via the 
# /${index}/_settings API. Unless all settings are dynamic all indices must be closed 
# in order to apply the upgradeIndices created in the future should use index templates 
# to set default values. 
#
# Please ensure all required values are updated on all indices by executing: 
#
# curl -XPUT 'http://localhost:9200/_all/_settings?preserve_existing=true' -d '{
#  "index.number_of_replicas" : "0",
#  "index.number_of_shards" : "1"
# }'
# in Dev Tools
# PUT /_all/_settings
# {
#     "index" : {
#        "number_of_replicas" : 0
#    }
# }

# ---------------------------------- Various -----------------------------------
#
# Require explicit names when deleting indices:
#
#action.destructive_requires_name: true
#
# if the automatic index creation is disable,
# uncommit to allow X-pack to create the following indices
#
# action.auto_create_index: .monitoring*
#
# X-Pack settings
# security
xpack.security.enabled: false
# monitoring
xpack.monitoring.enabled: true
# graph
xpack.graph.enabled: false
# watcher
xpack.watcher.enabled: false
# machine learning - this pack is not support in Alpine Linux
xpack.ml.enabled: false